spring.application.name=QubitQuest

# db connection configs
spring.datasource.url=jdbc:mysql://localhost:3306/qubit_quest
spring.datasource.username=root
spring.datasource.password=neetamalviya

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api/v1
spring.profiles.active=local


jwt.secret-key=as9jsdfnasyurtfjjanhbkjasjasnjasjskjdshaskaslasnadsldskndssdaajdl

execution.service.url=https://qubitquest.onrender.com
