spring.application.name=QubitQuest

# db connection configs
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api/v1
spring.profiles.active=local


jwt.secret-key=${JWT_SECRET_KEY}

execution.service.url=https://qubitquest.onrender.com

# OpenRouter configuration
spring.ai.openai.base-url=https://openrouter.ai/api/v1
spring.ai.openai.api-key=${OPENROUTER_API_KEY}

# Chat model configuration
spring.ai.openai.chat.options.max-completion-tokens=6000
spring.ai.openai.chat.options.model=google/gemini-3-flash-preview
spring.ai.openai.chat.options.temperature=0
